---
title: "Final Project: World Happiness Index"
author: "Jessica Strait"
date: "4-24-2020"
output: html_notebook
---

## Front Matter

```{r} 
rm(list = ls())

# load packages
library(DataComputing)
library(mosaic)
library(tidyverse)
library(dplyr)
install.packages("party")
library(party)
```

## Guiding Questions

* **Which regions of the world are the happiest and why?**
  + *Which countries have seen a large change in happiness from 2018 to 2019?*
  + *What contributing factors make the largest changes in each region, and how does the residual factor in?*

## Data Access

```{r}
# Import the data sets for years 2018 and 2019
data2018 <- read.csv("C:\\Users\\jessl\\Desktop\\2018.csv")
data2019 <- read.csv("C:\\Users\\jessl\\Desktop\\2019.csv")
```

```{r}
# Import supporting data from R packages
install.packages("countrycode")
library(countrycode)
install.packages("gdata")
library(gdata)
```

```{r}
# Inspect my primary data sources
head(data2018, 5)
tail(data2018, 5)
count(data2018)
names(data2018)
str(data2018)
```


## Data Wrangling

```{r}
# Use a join to merge data from 2018 and 2019. Note that variables with .x are from 2018, and .y are from 2019.
happiness <- merge(data2018, data2019, by = "Country.or.region")
head(happiness, 10)
```

```{r}
# Convert country variable to a string so we can use the countrycode package. Double-check that it worked.
happiness$Country.or.region <- as.character(happiness$Country.or.region)
class(happiness$Country.or.region)
```

```{r}
# Time to start assigning continents to countries! I'll create a new variable using the countrycode package to assign the continents.
happiness <- happiness %>% mutate(Continent = countrycode(sourcevar = happiness$Country.or.region, origin = "country.name", destination = "continent"))
happiness
```

```{r}
# Let's look at some quick stats about our data table for 2018. We will want this information to do some predictions with machine learning.
favstats(~ Score.x, data = happiness)
```

```{r}
# Looking at the 2018 data, let's see how much of a contributing factor the Continent is. We know there are 152 cases by our favstats() function.
# First, turn our Continent variable into a factor so that we can run the ctree() function on it.
happiness$Continent <- as.factor(happiness$Continent)
# Use machine learning techniques from the party R package.
happy_continents2018 <- ctree(Overall.rank.x < (152/2) ~ Continent, data = happiness)
plot(happy_continents2018, type = "simple")
```


## Data Visualization











