---
title: "Preliminary EDA: Exploring World Happiness Data Project"
author: "Jessica Strait"
date: "4-7-2020"
output: html_notebook
---

## Front Matter

```{r} 
rm(list = ls())

# load packages
library(DataComputing)
library(mosaic)
library(tidyverse)
library(dplyr)
install.packages("countrycode")
library(countrycode)
install.packages("gdata")
library(gdata)
```

## Guiding Questions

* **Which regions of the world are the happiest and why?**
+ *Which countries have seen a large change in happiness from 2018 to 2019?*
+ *What contributing factors make the largest changes in each region?*
+ *What contributing factors make the largest change regardless of region?*

## Data Sources

The primary data sources used in this report are the 2018 and 2019 World Happiness Index reports. The reports are compiled and released by the Sustainable Development Solutions Network, and have been shared in prominent venues including the United Nations International Day of Happiness event. Gallup World Poll collects the data through global polling via the Cantril ladder; respondents rank the quality of their own lives on a scale of 1-10, from worst possible life to best possible life. Calculations then occur multiplying national data about contributing factors (such as life expectancy) to predict the effect of those factors on the country's average score. A "residual" value exists as the difference between the sum of the contributing factors and the actual average happiness score, which may include non-quantitative cultural aspects of citizenship in a country. The average sample size is about 1,000 people per country per year with a 95% confidence interval.

The data is not gathered to make predictions about happiness, but to analyze the happiness of each country and consider what social and cultural programs each year may have contributed the most to the happiness of the citizens. The project began in 2015, and a new report is published each year.

A case represents the happiness index and contributing factors for one individual country. I plan to merge the 2018 and 2019 data sets so that a case will then represent the happiness index of a country in either year. There are 156 cases for each year, so I will work with 312 cases in my merged data set.

The "score" variable will be far more important to me than the "overall rank" variable. Because I am interested in the change in happiness, I will want to find the difference in "score" across years, rather than "overall rank." This is because of the possibility that multiple countries all saw a change in score without rank changing significantly. I also plan to use the "country" variable in combination with the countrycode R package to match cases to continents and compute regional happinss scores. Finally, I intend to use each contributing factor variable to determine what factors are the most significant per region and what factors remain significant regardless of geographic location.

## Exploring the Data

## Defining Data Sources


## Links to Data Sources

https://worldhappiness.report/ for the history of the project and appendices describing statistical measures taken.
https://www.kaggle.com/unsdsn/world-happiness for a general summary of each factor and downloadable data for each year.
https://cran.r-project.org/web/packages/countrycode/countrycode.pdf for documentation on the countrycode R package and how it can be used.
https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html for documentation on how to use ggplot2 and the world map.

